pipeline:
  build:
    image: node:${NODE_VERSION}
    commands:
      - npm install
      - npm run lint
      - npm test
  slack:
    image: plugins/slack
    username: drone
    channel: alerts
    secrets: [ slack_webhook ]
matrix:
  NODE_VERSION:
    - 6
    - 8